bootstrap.servers=b-broker-1:9092,b-broker-2:9092,b-broker-3:9092
group.id=payments-poc
enable.auto.commit=false
auto.offset.reset=earliest
isolation.level=read_committed
metadata.recovery.strategy=rebootstrap
metadata.recovery.rebootstrap.trigger.ms=30000
security.protocol=PLAINTEXT
