bootstrap.servers=a-broker-1:9092,a-broker-2:9092,a-broker-3:9092
acks=all
enable.idempotence=true
metadata.recovery.strategy=rebootstrap
metadata.recovery.rebootstrap.trigger.ms=30000
security.protocol=PLAINTEXT
