# DC2 controller 1 - POC only
process.roles=controller
node.id=1

controller.quorum.voters=1@b-ctrl-1:9093,2@b-ctrl-2:9093,3@b-ctrl-3:9093
controller.listener.names=CONTROLLER
listeners=CONTROLLER://0.0.0.0:9093

inter.broker.listener.name=BROKER
listener.security.protocol.map=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT

log.dirs=/var/lib/kafka/controller-1
