apiVersion: v2
name: prometheus-node-exporter
description: A Helm chart for prometheus node-exporter
keywords:
  - node-exporter
  - prometheus
  - exporter
type: application
version: 4.22.0
appVersion: 1.6.0

