# Local object on Cluster A, remote cluster is B.
# Bidirectional mode is useful for active/passive DR exercises and failback.
bootstrap.servers=b-broker-1:9092,b-broker-2:9092,b-broker-3:9092
link.mode=BIDIRECTIONAL
consumer.offset.sync.enable=true
consumer.offset.group.filters={"groupFilters":[{"name":"*","patternType":"LITERAL","filterType":"INCLUDE","topicTypes":["REMOTE_MIRROR"]}]}
consumer.offset.sync.ms=5000
topic.config.sync.ms=5000
mirror.start.offset.spec=earliest
acl.sync.enable=false
