apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: "2022-07-08T10:34:04Z"
  name: gft-academy-protaus
  namespace: default
data:
  database: amRiYzpwb3N0Z3Jlc3FsOi8vL3Byb3RhdXM/Y2xvdWRTcWxJbnN0YW5jZT1wb2wtcmVwb3J0emVuLWRldi0wMDU6ZXVyb3BlLXdlc3QyOnNxbC1yZXBvcnR6ZW4=
  password: cHJvdGF1c3VzZXI=
  username: cHJvdGF1cw==
